name: HEXO CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: hexo deploy with-hook
        # You may pin to the exact commit or the version.
        # uses: yuzhishuo/hexo-deploy-with-hook@c3937eca326bf45978aa1f9d592eb88dbbab5f13
        uses: yuzhishuo/hexo-deploy-with-hook@2.0.1
